FROM node:20.18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --legacy-peer-deps

RUN npm install -g next@latest

RUN npm install --save-exact --save-dev typescript @types/react @types/node --legacy-peer-deps

COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]
