FROM node:20.18-alpine as BUILDER

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

FROM node:20.18-alpine

WORKDIR /usr/src/app

COPY --from=BUILDER /usr/src/app /usr/src/app/

COPY wait-for-it.sh /usr/src/app/wait-for-it.sh

RUN chmod +x /usr/src/app/wait-for-it.sh

EXPOSE 8888

CMD ["./wait-for-it.sh", "db:3307", "--", "npx", "prisma", "generate", "&&", "npx", "prisma", "db", "push", "&&", "npm", "run", "start:prod"]
